version: '3'
services:
  otel-agent:
    container_name: collector
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-agent-config.yaml" ]
    volumes:
      - ./otel-agent-config.yaml:/etc/otel-agent-config.yaml
    ports:
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
#      - "4318:4318"   # OTLP http receiver

#  webapp:
#    container_name: webapp
#    build: .
#    ports:
#      - "8654:8654"
